### ISSUE TITLE
Make it possible to localize PH/SH names.

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#138]
#118.

Problem is that currently PH/SH names are defined in local language, to look them up, they would need to be changed to the English equivalent (which hopefully exists). Low priority.

**Comment by ypid** [comment]
Closing as out-of-scope for now.

**Comment by MarcelWaldvogel** [comment]
I would like to reconsider this:

I'm in the process of adding the holidays for Switzerland. With our four official languages, just picking one seems insufficient. However, there does not seem support for multi-language support within a given country.

A possible work-around could be to name the holidays on a state-by-state level, based on the dominant language in that state. However, there are multiple states in Switzerland which are bilingual, so this would not really solve the problem.

So having something like 'name[fr]' (or whatever syntax you prefer) would be great.

**Comment by ypid** [comment]
Hi, thanks for picking up ch definitions!

The name is not important to the library or the evaluation. It is currently shown as comment but this is kinda random behavior. Adding more translations to holiday definitions does not really add value in my point of view. Am I missing something?

If you want to add them I would suggest something like:

```
---

_nominatim_url: 'https://nominatim.openstreetmap.org/reverse?format=json&lat=49.5487&lon=9.8160&zoom=18&addressdetails=1&accept-language=de,en'

PH:  # https://de.wikipedia.org/wiki/Feiertage_in_Deutschland
  - {'name': 'Neujahrstag', 'name_de-de': 'Neujahrstag', 'fixed_date': [1, 1]}

Baden-Württemberg:
  _state_code: bw
  _nominatim_url: 'https://nominatim.openstreetmap.org/reverse?format=json&lat=49.5487429714954&lon=9.81602098644987&zoom=18&addressdetails=1'
  SH:
    - name: Osterferien
      'name_de-de': Osterferien
      'name_XX': Osterferien
      '2012': [4, 2, 4, 13]
```

https://en.wikipedia.org/wiki/IETF_language_tag
