### ISSUE TITLE
There are no holidays (PH) defined for country CI (Ivory Coast)

### ISSUE THREAD

**Issue by sommerluk** [opening-hours/opening_hours.js#262]
There are no holidays (PH) defined for country CI (Ivory Coast).

In Ivory Coast, all public holidays apply to the hole country. There are no regional differences.

I’ve updated the (french) wikipedia page with current and verified holiday informations for Ivory Coast: https://fr.wikipedia.org/wiki/Jour_f%C3%A9ri%C3%A9#_C%C3%B4te_d%27Ivoire

The comment “Également férié est le lendemain chaque fois que ladite fête tombe un dimanche.” means that, if this holiday is on sunday, both sunday and the following monday are holidays.

I could translate also the rest it if necessary…

**Comment by sommerluk** [comment]
date | name (from official government decision 2011-371) |  translation | comment
-- | -- | -- | --
1 January | Fête du 1er janvier |New Year
variable (1 day after Easter) | Lundi de Pâques |Easter Monday
1 May | Fête du travail |Labour day | If this holiday is on Sunday, both Sunday and the following Monday are holidays.
variable (on Thursday, 39 days after Easter) | Jour de l’Ascension |Feast of the Ascension |
variable (on Monday, 50 days after Easter) | Lundi de la Pentecôte |Monday after Pentecost 
7 August | Fête nationale |National Day | If this holiday is on Sunday, both Sunday and the following Monday are holidays.
15 August | Fête de l’Assomption |Assumption of Mary 
1 November | Fête de la Toussaint | All Saints’Day
15 November | Journée Nationale de la Paix | National Peace Day
25 December | Fête de Noël |Christmas | If this holiday is on Sunday, both Sunday and the following Monday are holidays.
variable (12 Rabi' al-awwal, Islamic calendar) | Lendemain de l’anniversaire de la naissance du Prophète Mahomet (Maouloud) |Mawlid al-Nabi al-Sharif
variable (one of the nights of the last ten days of Ramadan, Islamic calendar) | Lendemain de la nuit du destin (Laïlatou-Kadr) |Night of Destiny (Laylat al-Qadr)
variable (1 Shawwal, Islamic calendar) | Fête du Ramadan (Aîd-El-Fitr) |Eid al-Fitr | If this holiday is on Sunday, both Sunday and the following Monday are holidays.
variable (10 Dhu al-Hijjah, Islamic calendar) |Fête de la Tabaski (Aîd-El-Kébir) |Eid al-Adha, Festival of Sacrifice | If this holiday is on Sunday, both Sunday and the following Monday are holidays.

At least the civil and Christian public holidays should be easy to implement. Islamic holidays (the last four lines in the table) might be more difficult to calculate.

**Comment by ypid** [comment]
﻿Thanks very much. Translating is not necessary. Local language is preferred. Please refer to the docs: https://github.com/opening-hours/opening_hours.js#holidays-1

Please give it a try.

**Comment by sommerluk** [comment]
Hm.

The documentation mentions the file `opening_hours.js` which I cannot find within the repository…

The structure seems to have changes since the mentioned “example” PR #125 so I’ve used #239 as model.

First try:

```
---

# TODO _nominatim_url: 'https://nominatim.openstreetmap.org/reverse?format=json&lat=49.5487&lon=9.8160&zoom=18&addressdetails=1&accept-language=de,en'

PH:  # https://fr.wikipedia.org/wiki/Jour_f%C3%A9ri%C3%A9#_C%C3%B4te_d%27Ivoire
  - {'name': 'Fête du 1ᵉʳ janvier', 'fixed_date': [1, 1]}
  - {'name': 'Lundi de Pâques', 'variable_date': easter, 'offset': 1}
  - {'name': 'Fête du travail', 'fixed_date': [5, 1]}
  - {'name': 'Jour de l’Ascension', 'variable_date': easter, 'offset': 39}
  - {'name': 'Lundi de la Pentecôte', 'variable_date': easter, 'offset': 50}
  - {'name': 'Fête nationale', 'fixed_date': [8, 7]}
  - {'name': 'Fête de l’Assomption', 'fixed_date': [8, 15]}
  - {'name': 'Fête de la Toussaint', 'fixed_date': [11, 1]}
  - {'name': 'Journée Nationale de la Paix', 'fixed_date': [11, 15]}
  - {'name': 'Fête de Noël', 'fixed_date': [12, 25]}

```

Only the holidays with fixed date and those with an offset to Easter.

How to support that for some of these, if they are on Sunday, also the next Monday is a public holiday, but only then? It seems that https://github.com/opening-hours/opening_hours.js/blob/ceb098c038c2e0ef2daabbfbf1ab6a9612c19678/index.js#L2755 doesn’t help here?

**Comment by ypid** [comment]
Thanks! Also thanks for making me aware of the issues with the docs, I will fix them later.

For a PH which can be on Monday and Sunday please refer to https://github.com/opening-hours/opening_hours.js/pull/255. In fact, the format was changed as you noticed exactly for that reason to support such a thing.

**Comment by sommerluk** [comment]
Okay. I see your reference to “St Patrick’s Day”.

It seems that `getMovableEventsForYear` may return empty values for some years, so `nextMo-Fr17March` returns nothing when 17 march is on Monday to Friday, right?

I’ve taken a look to the code of `getMovableEventsForYear` but that’s a little bit beyond my knowledge.

However, what we would need is:
- a function that returns 2 May if the 1 May is a Sunday, otherwise nothing
- a function that returns 8 August if the 7 August is a Sunday, otherwise nothing
- a function that returns 26 December if the 25 December is a Sunday, otherwise nothing

Alternatively, this would give us the same result with slightly shorter code, but the logic is not intuitive any more the code would be less readable:
- a function that returns 2 May if this is a Monday, otherwise nothing
- a function that returns 8 August if this is a Monday, otherwise nothing
- a function that returns 26 December if this is a Monday, otherwise nothing

By the way: What is the Nominatim URL for? I don’t know what to do with this. (Anyway, `be.yaml` hasn’t a Nominatim URL at all.)

**Comment by ypid** [comment]
Thanks, I will look into the needed functions and write them in a few days.

About the Nominatim URL please have a look at [the docs](
https://github.com/opening-hours/opening_hours.js/blob/master/holidays/README.md#deciding-which-holidays-do-apply) and maybe other files like `de.yaml`.

**Comment by sommerluk** [comment]
> I will look into the needed functions and write them in a few days.

Thanks!

> About the Nominatim URL please have a look at the docs and maybe other files like de.yaml.

Okay, got it. So `be.yaml` is broken because it hasn’t a Nominatim URL, right?

Here comes an updated `ci.yaml` with Nominatim URL, updated comments (explaining why it isn’t useful to support Islamic holidays here) and containing the label data for the complex cases.

```yaml
---

_nominatim_url: 'https://nominatim.openstreetmap.org/reverse?format=json&lat=5.3203570&lon=-4.0161070&zoom=18&addressdetails=1&accept-language=fr'

# https://fr.wikipedia.org/wiki/Jour_f%C3%A9ri%C3%A9#_C%C3%B4te_d%27Ivoire
# In the Islamic calender, the start of a month depends on the local
# observation of the moon with the naked eye and therefore on the weather
# conditions. So the date exact and confirmed of the four public holidays in
# Ivory Coast that depend on the Islamic calender is known only shortly before.
# Therefore, they are not supported here.

PH:
  - {'name': 'Fête du 1ᵉʳ janvier', 'fixed_date': [1, 1]}
  - {'name': 'Lundi de Pâques', 'variable_date': easter, 'offset': 1}
  - {'name': 'Fête du travail', 'fixed_date': [5, 1]}
  - {'name': 'Lendemain de la Fête du travail', 'variable_date': 'if_1May_is_sunday_than_2May_else_nothing'}
  - {'name': 'Jour de l’Ascension', 'variable_date': easter, 'offset': 39}
  - {'name': 'Lundi de la Pentecôte', 'variable_date': easter, 'offset': 50}
  - {'name': 'Fête nationale', 'fixed_date': [8, 7]}
  - {'name': 'Lendemain de la Fête nationale', 'variable_date': 'if_7August_is_sunday_than_8August_else_nothing'}
  - {'name': 'Fête de l’Assomption', 'fixed_date': [8, 15]}
  - {'name': 'Fête de la Toussaint', 'fixed_date': [11, 1]}
  - {'name': 'Journée Nationale de la Paix', 'fixed_date': [11, 15]}
  - {'name': 'Fête de Noël', 'fixed_date': [12, 25]}
  - {'name': 'Lendemain de la Fête de Noël', 'variable_date': 'if_25December_is_sunday_than_26December_else_nothing'}
 
```
