### ISSUE TITLE
Merge holiday definitions with kholidays?

### ISSUE THREAD

**Issue by ypid** [opening-hours/opening_hours.js#300]
I finally found an interesting collection of holiday definitions in https://github.com/KDE/kholidays. It would probably be worth cooperating/merging with kholidays somehow.

**Comment by ypid** [comment]
Hm, I missed that kholidays does not go down to state level (of Germany for example, ref: https://github.com/KDE/kholidays/blob/master/holidays/plan2/holiday_de_de). We in opening_hours.js do that to output accurate results.

I also checked International Components for Unicode (ICU) now which is widely used http://site.icu-project.org/. Same issue, also does not go down to the state level (ref: https://github.com/unicode-org/icu/blob/873e2db78070d3015a54f9d9aa81e97095cd9dba/icu4j/main/classes/core/src/com/ibm/icu/impl/data/HolidayBundle_de_DE.java).

So the search continues. If anybody finds a better source we could merge with, please ping me.

**Comment by pke** [comment]
Maybe its time for a dedicated curated Web API that could be used?

**Comment by ypid** [comment]
How does that solve the issue?

**Comment by pke** [comment]
An up to date API for public holidays I meant. It could be used during a build step to update the local copies of public holidays.

**Comment by ypid** [comment]
Sure but what should be the data source this API could provide? That is what this issue is about.

**Comment by HolgerJeromin** [comment]
IMHO he suggest a browser API like https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Intl

Than the browser vendors would have the responsability to provide the data.
But perhaps @pke suggested something different :-)

**Comment by pke** [comment]
Not sure what is so unclear. The API returns public holidays. They are entered there manually from someone, since the German government is unable to provide anything but PDFs for annual school holidays for instance.

I remember discussing this here before and voila: https://github.com/opening-hours/opening_hours.js/issues/192

The people of schulferien.org still haven't opened their data, have they?

**Comment by ypid** [comment]
I get your point. The thing is that it is unrelated to *this* issue.

> manually from someone

This goes more into what this issue is about. I am thinking of *one* place, where the international community (manually) tracks public and school holiday as Open Data for everybody to use because other commercial or government entities are unable to do that as we have experienced.

PS: Thanks again for contacting the German KMK :+1: 

> The people of schulferien.org still haven't opened their data, have they?

I have not checked recently, but I think I talked about this before. Their service depends on ads and they don’t want to lose control over the data.

**Comment by pke** [comment]
I think something like `POST /ger/nrw/2019-12-23/2020-01-06?name=Weihnachstferien` would be enough in the beginning to get the collection started?
The service could even have default date ranges to figure out the name of the (school) holidays itself.
Also there are rule based holidays like Thanks Giving that can be calculated without user input.

**Comment by ypid** [comment]
> I get your point. The thing is that it is unrelated to this issue.

Ok, to keep things structured I created #303. The discussion can be continued there.

**Comment by HolgerJeromin** [comment]
The smart home software openhab uses: https://github.com/svendiedrichsen/jollyday

**Comment by ypid** [comment]
Thanks, that also scrolled through my feed reader today. I now checked it quickly and it looks promising:

https://github.com/svendiedrichsen/jollyday/blob/master/src/main/resources/holidays/Holidays_de.xml
https://github.com/svendiedrichsen/jollyday/blob/master/src/main/resources/holidays/Holidays_ch.xml

**Comment by ypid** [comment]
And there is https://github.com/dr-prodigy/python-holidays but there are no plans to add school holiday support, ref: https://github.com/dr-prodigy/python-holidays/issues/249.

https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/germany.py

CC: @T-Born (ref: https://github.com/dr-prodigy/python-holidays/issues/249), @afaucogney (ref: https://github.com/dr-prodigy/python-holidays/issues/120)

**Comment by Lee-Carre** [comment]
> I am thinking of *one* place, where the international community (manually) tracks public and school holiday as Open Data for everybody to use

A comparable project, for inspiration, is the [time-zone database](http://www.iana.org/time-zones). Though, problems still occur when governments give little to zero notice of forthcoming changes, when distribution latency is non-zero.

On the point about machine-readable formats for easy importation, I wonder if some carefully-worded FoI requests might be worth a try. Not sure about other jurisdictions, but I vaguely recall that here (Jersey) one can at least request specific formats (or give clues as to intended usage, to enable the administrators to select an existing format). Might be something related to (if I recall) the legislation making mention of responses being in sane formats (I forget the precise wording: sane as we would define it; libre, standardised, easy to parse).

Is there no equivalent of http://data.gov.de/ which might host what you seek?

Pity that Germany isn't setting the example with this, what with the reputation for efficiency & doing things properly. Maybe that only applies once sensible rules & procedures are already established.

**Comment by hnryjms** [comment]
Hey all-

Stemming off this and #303-- I'm tempted to try and address some of [my own] issues around holidays with the following concept. I'll probably implement this someday soon when I have the time if nobody voices opposition. Generally, what I'm thinking is:

* Merge all the holiday timing/positioning files into a single `holidays:` block where each holiday has an ID. These IDs can be global (e.g. `"new-years"`) or regional (e.g. `usa-juneteenth` or `usa-ut-pioneer-day`).
* Replace `country_code`/`state_code` matchers for general object-matching of the OSM tags for a region (for example, a match of a 2 tag matcher takes higher priority than match of a 1 tag matcher).
* Update region-based matchers to use OSM-style tags
  * this should help solve some issues like #69 where Washington DC is not a state.
  * Also, some businesses observe holidays based on the owner's religion or culture, unrelated to geography. OSM tags can express this, but not Nominatim.
  * Maybe can keep this backwards-compatible by reformatting Nominatim back to OSM tag style (?)
* Update regions to only refer to holidays by their ID, so the rules can be reused at regions of varying levels (e.g. global, country, state, city // religious, cultural holidays)
* Change build code to merge all YAML files into a single in-memory dictionary/map/database/whatever-you-wanna-call-it ... to help readability
  * `holidays-global.yml`
  * `holidays-jewish.yml`
  * `us.yml`
  * `mx.yml`
* Add the ability on a specific `OpeningHours` instance to explicitly set a list of PH IDs, instead of using the matching logic above (e.g. if an app or service knows the specific holidays of the business)

Essentially, what I'm aiming for is a data structure like:

```yaml
holidays: # split across global+region files
  new-years-day:
    name: New Year's Eve
    "name:es": "Año Nuevo"
    fixed_date: [1, 1]
  usa-juneteenth:
    name: Juneteenth
    fixed_date: [6, 19]
  hannukkah:
    name: Hannukah
    fixed_date: [3, 25]
    calendar: hebrew # note: currently not suppoted, but included for conceptual purpose

regions: # split across many files
  - name: "United States" # unused, but helpful
    match:
      "addr:country": US
    PH:
      - new-years-day
  - name: "US > Minnesota"
    match:
      "addr:country": US
      "addr:state": MN
    PH:
      - new-years-day
      - usa-juneteenth
  - name: "Jewish"
    merge: true # tbd--combine this with any other matches (rather than replacing) ... maybe future scope
    match:
      religion: jewish
    PH:
      - hannukkah
```

Community-let me know your thoughts. Otherwise, I will open a PR for this once I have time to build it.
